### ISSUE TITLE
[Need assistance] On setting up infrastructure.

### ISSUE THREAD

**Issue by vishnuchalla** [quay/quay-performance-scripts#49]
I have tried creating infrastructure using the `terraform apply` as mentioned in the infrastructure README.md on our team cluster. When I perform a `terraform apply` below is the error which I come across.

```
│ Warning: Argument is deprecated
│ 
│   with aws_elasticache_replication_group.quay_build_redis,
│   on redis.tf line 5, in resource "aws_elasticache_replication_group" "quay_build_redis":
│    5:   replication_group_description = "${var.prefix} Replication Group"
│ 
│ Use description instead
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: creating ElastiCache Replication Group (vchalla-py3-build-redis-rep-group): InvalidParameterValue: eu-west-1 is not a valid availability zone.
│ 	status code: 400, request id: b959a576-9a19-48fe-ae36-3d903f09c77b
│ 
│   with aws_elasticache_replication_group.quay_build_redis,
│   on redis.tf line 1, in resource "aws_elasticache_replication_group" "quay_build_redis":
│    1: resource "aws_elasticache_replication_group" "quay_build_redis" {
│ 
╵
╷
│ Error: creating ElastiCache Cache Cluster: InvalidParameterValue: The account does not have any default subnets.
│ 	status code: 400, request id: 1ad44fe8-ce2d-4438-81c7-de7ddfef1f20
│ 
│   with aws_elasticache_cluster.quay_modelcache_redis,
│   on redis.tf line 30, in resource "aws_elasticache_cluster" "quay_modelcache_redis":
│   30: resource "aws_elasticache_cluster" "quay_modelcache_redis" {

```
I have tried changing the region for ElasticCache Replication Group and the same error appears for every region. 
And also our AWS account has default subnets verified that as well.

What is the resolution for the above errors? Any suggestions would be much helpful.

Thanks in Advance.

**Comment by syed** [comment]
`eu-west-1 is not a valid availability zone.
│ 	status code: 400, request id: b959a576-9a19-48fe-ae36-3d903f09c77b`

did you mean `us-west-1` ?

**Comment by vishnuchalla** [comment]
this try was for `eu-west-1`. But i also tried `us-west-1` as well but it did not work. Does it have anything to do with Quay Product being deployed on the same cluster?
